DEFINE VARIABLE h AS HANDLE NO-UNDO.
DEFINE VARIABLE a AS CHARACTER NO-UNDO.
FUNCTION sample2 RETURNS CHARACTER (INPUT-OUTPUT a AS CHARACTER) IN h.
RUN D:\vaishali\BlockProperties\super_func\main_driver.p PERSISTENT SET h.
RUN sample1 IN h (INPUT-OUTPUT a).
MESSAGE a VIEW-AS ALERT-BOX.
a = "".
MESSAGE sample2(a) VIEW-AS ALERT-BOX.
