PROCEDURE ipMessage:
    DEFINE INPUT PARAMETER ipchMessage AS CHARACTER NO-UNDO. 
    MESSAGE ipchMessage VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
END PROCEDURE.

PROCEDURE ipMessage1:
    DEFINE INPUT PARAMETER ipchMessage AS CHARACTER NO-UNDO.
    MESSAGE ipchMessage VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    
END PROCEDURE.

PROCEDURE ipMessage2:
    DEFINE INPUT PARAMETER ipchMessage AS CHARACTER NO-UNDO.
    MESSAGE ipchMessage VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
END PROCEDURE.

FUNCTION myfunc RETURNS CHAR (INPUT parm1 AS CHAR).
    MESSAGE "parm1"
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.

