DEFINE VAR hhandle AS HANDLE NO-UNDO.

RUN d:\vaishali\BlockProperties\persistent_pro\persistent_pro1.p PERSISTENT SET hHANDLE.  

MESSAGE hHandle:TYPE VIEW-AS ALERT-BOX INFORMATION BUTTON OK.

MESSAGE hHandle:INTERNAL-ENTRIES VIEW-AS ALERT-BOX INFORMATION BUTTON OK.

MESSAGE hHandle:GET-SIGNATURE("ipMessage") VIEW-AS ALERT-BOX INFORMATION BUTTON OK.

IF VALID-HANDLE(hHandle) THEN
DO:
    RUN ipMessage IN hHandle("Hello").
    RUN ipMessage1 IN hHANDLE("Hello User").
END.

DELETE PROCEDURE hHandle.
