DEFINE VAR viYear AS INT NO-UNDO.
DEF VAR vlAns AS LOGICAL INITIAL TRUE NO-UNDO.

DO WHILE vlAns:
    SET viYear.
    IF viYear MOD 4 = 0 THEN
        IF viYear MOD 100 = 0 THEN
            IF  viYear MOD 400 = 0 THEN
                MESSAGE viYear " IS A LEAP YEAR" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
            ELSE
                MESSAGE viYear " IS NOT A LEAP YEAR" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
        ELSE
            MESSAGE viYear " IS A LEAP YEAR" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    ELSE
        MESSAGE viYear " IS  NOT A LEAP YEAR" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
        
    MESSAGE "DO YOU WANT TO CONTINUE (YES/NO)" VIEW-AS ALERT-BOX INFORMATION BUTTONS YES-NO SET vlAns.
END.
