/*******Defined Input Parameter******************/
DEF INPUT PARAMETER selectedValue AS CHAR NO-UNDO.

/********if radioButton value is search************************/
IF selectedValue = "search" THEN
DO:
    PROMPT-FOR customer.cust-num WITH FRAME search-frame.
    FIND customer USING customer.cust-num NO-LOCK NO-ERROR.
    IF AVAILABLE customer THEN
        DISP customer EXCEPT cust-num WITH OVERLAY FRAME search-frame VIEW-AS DIALOG-BOX TITLE "Display Customer" 2 COLUMNS. 
    ELSE
        MESSAGE "Customer Search criterion is not valid". 
    WAIT-FOR "Go" OF THIS-PROCEDURE.
END.

/************if radioButton value is new**********************************/
ELSE DO:
    /*********Defined All Variables**********************************/
    DEF VAR cnum LIKE customer.cust-num VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cName LIKE customer.NAME VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cCountry LIKE customer.country INITIAL "U.S.A" VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cAddress LIKE customer.address VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cAddress2 LIKE customer.address2 VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cCity LIKE customer.city VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cState LIKE customer.state VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cPostalCode LIKE customer.postal-code FORMAT "99999-9999" VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cContact LIKE customer.contact FORMAT "9999999999" VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cSalesRep LIKE customer.sales-rep VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cPhone LIKE customer.phone FORMAT "(999)999-9999" VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cCreditLimit LIKE customer.credit-limit VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cBalance LIKE customer.balance VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cTerms LIKE customer.terms VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cDiscount LIKE customer.discount VIEW-AS FILL-IN NO-UNDO.
    DEF VAR cComments LIKE customer.comments VIEW-AS FILL-IN NO-UNDO.
    DEF VAR isValid AS LOGICAL NO-UNDO.
    
    /*************Define Frame create-frame************************************************/
    DEFINE FRAME create-frame 
       cnum cname cCountry cAddress cAddress2 cCity cState cPostalCode cContact cSalesRep cPhone cCreditLimit cBalance cTerms cDiscount cComments.
    
    VIEW FRAME create-frame.   
    
    /********AutoGenerated Value of customer number*************************/
    FIND LAST customer NO-LOCK NO-ERROR.
    IF AVAILABLE customer THEN
        cnum = customer.cust-num + 1.
    ELSE
        cnum = 1.        
    DISP cnum WITH FRAME create-frame.
    
    
    /************Taking input from user for all the fields except customer num*********************************/
    UPDATE cName cCountry cAddress cAddress2 cCity cState cPostalCode cContact cSalesRep cPhone cCreditLimit cBalance cTerms cDiscount cComments WITH FRAME create-frame 2 COLUMNS VIEW-AS DIALOG-BOX TITLE "Insert Customer".
    
    VIEW FRAME create-frame.
    
    DO WHILE NOT isValid:
    
        /************Validations applied - No field should be empty**************************/ 
        IF cname:SCREEN-VALUE = "" THEN
        DO:
           MESSAGE "Please Enter customer name" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
           APPLY "Entry" TO cname.
           isvalid = FALSE.
        END.
        
        ELSE IF cAddress:SCREEN-VALUE = "" THEN
        DO:
           MESSAGE "Please Enter customer Address" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
           APPLY "Entry" TO cAddress.
           isvalid = FALSE.
        END.
        
        ELSE IF cCity:SCREEN-VALUE = "" THEN
        DO:
           MESSAGE "Please Enter customer City" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
           APPLY "Entry" TO cCity.
           isvalid = FALSE.
        END.     
        
        ELSE IF cState:SCREEN-VALUE = "" THEN
        DO:
           MESSAGE "Please Enter customer State" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
           APPLY "Entry" TO cState.
           isvalid = FALSE.
        END.
           
        ELSE IF cSalesRep:SCREEN-VALUE = "" THEN
        DO:
           MESSAGE "Please Enter salesRep" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
           APPLY "Entry" TO cSalesRep. 
           isvalid = FALSE.
        END.        
        
        ELSE IF cContact:SCREEN-VALUE = "" THEN
        DO:
           MESSAGE "Please Enter Customer Contact" VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
           APPLY "Entry" TO cContact. 
           isvalid = FALSE.
        END.
        ELSE
            isvalid = TRUE.
        
        ENABLE ALL EXCEPT cnum WITH FRAME create-frame.  
        WAIT-FOR 'GO' OF cComments OR 'return' OF cComments.
    
    END.
    /*************Create Customer Record in database**************************/
    CREATE customer.
    
    /*********If SalesRep does not exist in salesrep table, then create a new record in salesRep table***************/
    FIND FIRST salesrep WHERE salesRep.sales-rep = CSalesRep NO-LOCK NO-ERROR.
    IF NOT AVAILABLE salesrep THEN
    DO:
        CREATE salesrep.
        salesrep.sales-rep = CSalesRep.
    END.
    ASSIGN customer.cust-num = cnum
           customer.country = cCountry:SCREEN-VALUE
           customer.NAME = cName:SCREEN-VALUE
           customer.address = cAddress:SCREEN-VALUE
           customer.address2 = cAddress2:SCREEN-VALUE
           customer.city = cCity:SCREEN-VALUE
           customer.state = cState:SCREEN-VALUE
           customer.postal-code = cPostalCode:SCREEN-VALUE
           customer.contact = cContact:SCREEN-VALUE
           customer.phone = cPhone:SCREEN-VALUE
           customer.sales-rep = cSalesRep:SCREEN-VALUE
           customer.credit-limit = DECIMAL(cCreditLimit:SCREEN-VALUE)
           customer.balance = DECIMAL(cBalance:SCREEN-VALUE)
           customer.terms = cTerms:SCREEN-VALUE
           customer.discount = DECIMAL ( TRIM ( CDiscount:SCREEN-VALUE IN FRAME create-frame, "%" ) )
           customer.comments = cComments:SCREEN-VALUE. 
 END.
