DEFINE TEMP-TABLE TTCustomer NO-UNDO LIKE customer.
DEFINE INPUT PARAMETER TABLE FOR TTCustomer.
DEFINE INPUT PARAMETER rwTTCust AS ROWID NO-UNDO.

FIND TTcustomer WHERE ROWID(TTCustomer) = rwTTCust NO-LOCK NO-ERROR.
CREATE customer.
BUFFER-COPY TTCustomer TO customer.
